name       : vagrant
version    : 2.0.0
release    : 9
source     :
    - https://github.com/mitchellh/vagrant/archive/v2.0.0.tar.gz : c25d3a5f18abdf349047f4d80bb74e6cb526959536e4bef5aa771de9d39cb260
homepage   : https://www.vagrantup.com/
license    : MIT
component  : programming.tools
summary    : Build and distribute virtualized development environments
description: |
    Create and configure lightweight, reproducible, and portable development environments.
networking : yes
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby-devel
    - libarchive-bin
setup      : |
    %patch -p1 < $pkgfiles/disable-installer-warning.patch
build      : |
    gem build vagrant.gemspec
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$installdir$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install vagrant-${version}.gem --no-ri --no-rdoc
    ln -s $GEM_PATH/vagrant-${version}/lib/vagrant $installdir/usr/lib64/vagrant
    install -D -d -m 00755 $installdir/usr/bin
    ln -s $GEM_PATH/bin/vagrant $installdir/usr/bin/vagrant
    install -Dm644 contrib/bash/completion.sh $installdir/usr/share/bash-completion/completions/vagrant
