name       : vagrant
version    : 1.9.3
release    : 4
source     :
    - https://github.com/mitchellh/vagrant/archive/v1.9.3.tar.gz : 4b141f60e7e59e654b9a77eb137f208613349db331cdbfcd9a8354b8ebba5c00
homepage   : https://www.vagrantup.com/
license    : MIT
component  : programming.tools
summary    : Build and distribute virtualized development environments
description: |
    Create and configure lightweight, reproducible, and portable development environments.
networking : yes
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.2)
rundeps    :
    - ruby-devel
    - libarchive-bin
setup      : |
    %patch -p1 < $pkgfiles/disable-installer-warning.patch
    gem build vagrant.gemspec
build      : |
    export NOKOGIRI_USE_SYSTEM_LIBRARIES=1
    export GEM_PATH=$installdir/usr/lib64/ruby/gems/2.2.0
    export GEM_HOME=$GEM_PATH
    gem install vagrant-${version}.gem --no-ri --no-rdoc
install    : |
    cp -r lib $installdir/usr/lib64/ruby/gems/2.2.0/gems/vagrant-${version}
    ln -s /usr/lib64/ruby/gems/2.2.0/gems/vagrant-${version}/lib/vagrant $installdir/usr/lib64/vagrant
    install -Dm755 bin/vagrant $installdir/usr/bin/vagrant
    install -Dm644 contrib/bash/completion.sh $installdir/usr/share/bash-completion/completions/vagrant
