name       : vagrant
version    : 1.9.5
release    : 6
source     :
    - https://github.com/mitchellh/vagrant/archive/v1.9.5.tar.gz : 69eb8ede3148b6f94389be5fd2d6cb2b6c79ba78cbcacdc354d2c73f12eccc2a
homepage   : https://www.vagrantup.com/
license    : MIT
component  : programming.tools
summary    : Build and distribute virtualized development environments
description: |
    Create and configure lightweight, reproducible, and portable development environments.
networking : yes
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - ruby-devel
    - libarchive-bin
setup      : |
    %patch -p1 < $pkgfiles/disable-installer-warning.patch
    gem build vagrant.gemspec
build      : |
    export GEM_PATH=$installdir/usr/lib64/ruby/gems/2.2.0
    export GEM_HOME=$GEM_PATH
    gem install vagrant-${version}.gem --no-ri --no-rdoc
install    : |
    cp -r lib $installdir/usr/lib64/ruby/gems/2.2.0/gems/vagrant-${version}
    ln -s /usr/lib64/ruby/gems/2.2.0/gems/vagrant-${version}/lib/vagrant $installdir/usr/lib64/vagrant
    install -D -d -m 00755 $installdir/usr/bin
    ln -s /usr/lib64/ruby/gems/2.2.0/bin/vagrant $installdir/usr/bin/vagrant
    install -Dm644 contrib/bash/completion.sh $installdir/usr/share/bash-completion/completions/vagrant
